// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenCityManagement.Migrations
{
    [DbContext(typeof(GreenCityContext))]
    [Migration("20260223114540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenCityManagement.Models.District", b =>
                {
                    b.Property<int>("ID_district")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_district"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_district");

                    b.ToTable("District", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.Employee", b =>
                {
                    b.Property<int>("ID_employee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_employee"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_employee");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.Maintenance", b =>
                {
                    b.Property<int>("ID_maintenance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_maintenance"));

                    b.Property<int>("ID_plant")
                        .HasColumnType("int");

                    b.Property<int>("ID_work_type")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Work_date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_maintenance");

                    b.HasIndex("ID_plant");

                    b.HasIndex("ID_work_type");

                    b.ToTable("Maintenance", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.Plant", b =>
                {
                    b.Property<int>("ID_plant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_plant"));

                    b.Property<string>("Health_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_district")
                        .HasColumnType("int");

                    b.Property<int>("ID_plant_type")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Planting_date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_plant");

                    b.HasIndex("ID_district");

                    b.HasIndex("ID_plant_type");

                    b.ToTable("Plant", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.PlantEmployee", b =>
                {
                    b.Property<int>("ID_plant_employee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_plant_employee"));

                    b.Property<int>("ID_employee")
                        .HasColumnType("int");

                    b.Property<int>("ID_plant")
                        .HasColumnType("int");

                    b.HasKey("ID_plant_employee");

                    b.HasIndex("ID_employee");

                    b.HasIndex("ID_plant");

                    b.ToTable("Plant_Employee", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.PlantPassport", b =>
                {
                    b.Property<int>("ID_passport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_passport"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ID_plant")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_inspection_date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_passport");

                    b.HasIndex("ID_plant")
                        .IsUnique();

                    b.ToTable("PlantPassport", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.PlantType", b =>
                {
                    b.Property<int>("ID_plant_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_plant_type"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_plant_type");

                    b.ToTable("PlantType", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.WorkType", b =>
                {
                    b.Property<int>("ID_work_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_work_type"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_work_type");

                    b.ToTable("WorkType", (string)null);
                });

            modelBuilder.Entity("GreenCityManagement.Models.Maintenance", b =>
                {
                    b.HasOne("GreenCityManagement.Models.Plant", "Plant")
                        .WithMany("Maintenances")
                        .HasForeignKey("ID_plant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenCityManagement.Models.WorkType", "WorkType")
                        .WithMany("Maintenances")
                        .HasForeignKey("ID_work_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("GreenCityManagement.Models.Plant", b =>
                {
                    b.HasOne("GreenCityManagement.Models.District", "District")
                        .WithMany("Plants")
                        .HasForeignKey("ID_district")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenCityManagement.Models.PlantType", "PlantType")
                        .WithMany("Plants")
                        .HasForeignKey("ID_plant_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("PlantType");
                });

            modelBuilder.Entity("GreenCityManagement.Models.PlantEmployee", b =>
                {
                    b.HasOne("GreenCityManagement.Models.Employee", "Employee")
                        .WithMany("PlantEmployees")
                        .HasForeignKey("ID_employee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenCityManagement.Models.Plant", "Plant")
                        .WithMany("PlantEmployees")
                        .HasForeignKey("ID_plant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenCityManagement.Models.PlantPassport", b =>
                {
                    b.HasOne("GreenCityManagement.Models.Plant", "Plant")
                        .WithOne("PlantPassport")
                        .HasForeignKey("GreenCityManagement.Models.PlantPassport", "ID_plant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenCityManagement.Models.District", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GreenCityManagement.Models.Employee", b =>
                {
                    b.Navigation("PlantEmployees");
                });

            modelBuilder.Entity("GreenCityManagement.Models.Plant", b =>
                {
                    b.Navigation("Maintenances");

                    b.Navigation("PlantEmployees");

                    b.Navigation("PlantPassport")
                        .IsRequired();
                });

            modelBuilder.Entity("GreenCityManagement.Models.PlantType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GreenCityManagement.Models.WorkType", b =>
                {
                    b.Navigation("Maintenances");
                });
#pragma warning restore 612, 618
        }
    }
}
